
export const API_URL_DATA = [
  { id: 1, title: 'Top Stories Today', title_slug: 'top-stories-today', playlist_id: 'x7h89j', isPlaylist: false },
  { id: 2, title: 'Trending Videos', title_slug: 'trending-videos', playlist_id: 'x7h89k', isPlaylist: false },
  { id: 3, title: 'Latest News', title_slug: 'latest-news', playlist_id: 'x85uxc', isPlaylist: false },
  { id: 4, title: 'Featured Playlists', title_slug: 'featured-playlists', playlist_id: 'x860li,x7h72r,x86asy,x7h750,x7h752,x7h761,x7h8av,x7h75w', isPlaylist: true },
  { id: 5, title: 'Politics', title_slug: 'politics', playlist_id: 'x86asm', isPlaylist: false },
  { id: 6, title: 'News Point', title_slug: 'news-point', playlist_id: 'x86at6', isPlaylist: false },
  { id: 7, title: 'More in News', title_slug: 'more-in-news', playlist_id: 'x7h6to,x7h6t7,x7h6tg,x7h6u0,x7h6u5,x7h6zp,x7h731,x7h73y,x7h73x', isPlaylist: true },
  { id: 8, title: 'City News', title_slug: 'city-news', playlist_id: 'x7h72r,x7h731,x7h73p,x7h73v,x7h73x,x7h73y,x7h74c,x7h74l,x7h74t', isPlaylist: true },
  { id: 9, title: 'Thet from the Set', title_slug: 'theft-from-the-set', playlist_id: 'x7h76b', isPlaylist: false },
  { id: 10, title: 'Celebrity Gossips', title_slug: 'celebrity-gossips', playlist_id: 'x7h765', isPlaylist: false },
  { id: 11, title: 'Featured Channels', title_slug: 'featured-channels', playlist_id: 'lokmatonline', isPlaylist: true },
  { id: 12, title: 'Marathi Entertainment', title_slug: 'marathi-entertainment', playlist_id: 'x7h761,x7h7to,x7h767,x7h7us,x7h7uy,x7h7v1,x7h7v4', isPlaylist: true },
  { id: 13, title: 'Sope Upay', title_slug: 'sope-upay', playlist_id: 'x7h74r', isPlaylist: false },
  { id: 14, title: 'Events & Festival', title_slug: 'events-and-festival', playlist_id: 'x7h751', isPlaylist: false },
  // { id: 15, title: 'Lokmat Events', title_slug: 'lokmat-events', playlist_id: 'x7h752,x7h757,x7h75k,x7h75v,x7h75y,x7h760', isPlaylist: true },
  // { id: 16, title: 'Bhakti', title_slug: 'bhakti', playlist_id: 'x7h752,x7h757,x7h75k,x7h75v,x7h75y,x7h760', isPlaylist: true },
  { id: 17, title: 'Shopping', title_slug: 'shopping', playlist_id: 'x7h76j', isPlaylist: false },
  { id: 18, title: 'Home Remedies', title_slug: 'home-remedies', playlist_id: 'x7h76l', isPlaylist: false },
  // { id: 19, title: 'Sakhi', title_slug: 'sakhi', playlist_id: 'x7h766,x7h76p,x7h78s,x7h7t5,x7h7t9,x7h7tf,x7h7tj', isPlaylist: true },
  // { id: 20, title: 'Beyond Boundaries', title_slug: 'beyond-boundaries', playlist_id: 'x7h75a', isPlaylist: false },
  // { id: 21, title: 'Lokmat Events', title_slug: 'lokmat-events', playlist_id: 'x7vjwd,x7mmzk,x7mmzl,x7h774,x7h776,x7h777,x7h77b', isPlaylist: true },
  // { id: 22, title: 'Latest Viral Videos', title_slug: 'latest-viral-videos', playlist_id: 'x7h75u', isPlaylist: false },
];